
FROM golang:1.26-alpine AS builder


RUN apk add --no-cache gcc musl-dev

RUN go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

FROM alpine:latest
RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/migrate /usr/local/bin/migrate

ENTRYPOINT ["migrate"]