// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"database/sql"
	"time"
)

type Alert struct {
	ID              int64
	Source          string
	Severity        string
	Description     sql.NullString
	IpAddress       sql.NullString
	EnrichmentType  sql.NullString
	SourceCreatedAt time.Time
	CreatedAt       time.Time
	FetchHistoryID  sql.NullInt64
}

type AlertFetchHistory struct {
	ID         int64
	ScannedAt  time.Time
	Reattempts sql.NullInt64
	Success    bool
	Reason     sql.NullString
}
