// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package data

import (
	"context"
	"database/sql"
	"time"
)

const addAlert = `-- name: AddAlert :exec
INSERT INTO alerts (
    source, 
    severity, 
    description, 
    source_created_at,
    enrichment_type,
    ip_address,
    fetch_history_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type AddAlertParams struct {
	Source          string
	Severity        string
	Description     sql.NullString
	SourceCreatedAt time.Time
	EnrichmentType  sql.NullString
	IpAddress       sql.NullString
	FetchHistoryID  sql.NullInt64
}

func (q *Queries) AddAlert(ctx context.Context, arg AddAlertParams) error {
	_, err := q.db.ExecContext(ctx, addAlert,
		arg.Source,
		arg.Severity,
		arg.Description,
		arg.SourceCreatedAt,
		arg.EnrichmentType,
		arg.IpAddress,
		arg.FetchHistoryID,
	)
	return err
}

const addScanResult = `-- name: AddScanResult :one
INSERT into alert_fetch_history (
    reattempts,
    success,
    reason,
    scanned_at
) VALUES (
    ?, ?, ?, ?
) RETURNING id
`

type AddScanResultParams struct {
	Reattempts sql.NullInt64
	Success    bool
	Reason     sql.NullString
	ScannedAt  time.Time
}

func (q *Queries) AddScanResult(ctx context.Context, arg AddScanResultParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addScanResult,
		arg.Reattempts,
		arg.Success,
		arg.Reason,
		arg.ScannedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const alerts = `-- name: Alerts :many
SELECT id, source, severity, description, ip_address, enrichment_type, source_created_at, created_at, fetch_history_id FROM alerts
ORDER BY source_created_at DESC, id DESC
  LIMIT ?
  OFFSET ?
`

type AlertsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) Alerts(ctx context.Context, arg AlertsParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, alerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Severity,
			&i.Description,
			&i.IpAddress,
			&i.EnrichmentType,
			&i.SourceCreatedAt,
			&i.CreatedAt,
			&i.FetchHistoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAlerts = `-- name: CountAlerts :one
SELECT COUNT(*) FROM alerts
`

func (q *Queries) CountAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lastSuccessfulSync = `-- name: LastSuccessfulSync :one
SELECT id, scanned_at, reattempts, success, reason FROM alert_fetch_history
   WHERE success == 1
   ORDER BY datetime(substr(scanned_at, 1, 19)) DESC
   LIMIT 1
`

func (q *Queries) LastSuccessfulSync(ctx context.Context) (AlertFetchHistory, error) {
	row := q.db.QueryRowContext(ctx, lastSuccessfulSync)
	var i AlertFetchHistory
	err := row.Scan(
		&i.ID,
		&i.ScannedAt,
		&i.Reattempts,
		&i.Success,
		&i.Reason,
	)
	return i, err
}

const lastSyncs = `-- name: LastSyncs :many
SELECT id, scanned_at, reattempts, success, reason from alert_fetch_history
    ORDER BY datetime(substr(scanned_at, 1, 19)) DESC
    LIMIT ?
`

func (q *Queries) LastSyncs(ctx context.Context, limit int64) ([]AlertFetchHistory, error) {
	rows, err := q.db.QueryContext(ctx, lastSyncs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertFetchHistory
	for rows.Next() {
		var i AlertFetchHistory
		if err := rows.Scan(
			&i.ID,
			&i.ScannedAt,
			&i.Reattempts,
			&i.Success,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentScanErrors = `-- name: RecentScanErrors :many
SELECT id, scanned_at, reattempts, success, reason FROM alert_fetch_history
    WHERE success == 0
      -- Take the first 19 characters (YYYY-MM-DD HH:MM:SS) because sqlite can't understand rfc3339
      AND datetime(substr(scanned_at, 1, 19)) >= datetime('now', ?) 
    ORDER BY scanned_at DESC
    LIMIT ?
`

type RecentScanErrorsParams struct {
	Datetime interface{}
	Limit    int64
}

func (q *Queries) RecentScanErrors(ctx context.Context, arg RecentScanErrorsParams) ([]AlertFetchHistory, error) {
	rows, err := q.db.QueryContext(ctx, recentScanErrors, arg.Datetime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertFetchHistory
	for rows.Next() {
		var i AlertFetchHistory
		if err := rows.Scan(
			&i.ID,
			&i.ScannedAt,
			&i.Reattempts,
			&i.Success,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
